image: python:3.8

stages:
  - greeting
  - lint
  - test
  - integration

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'

greet:
  stage: greeting
  script:
    - echo "Hello! My name is $MY_LOGIN. My password is $MY_PASSWORD."

flake8:
  stage: lint
  before_script:
    - pip install flake8
  script:
    - flake8 .
  allow_failure: true

unit-tests:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest tests/unit

integration-tests:
  stage: integration
  needs:
    - unit-tests
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest tests/integration
  when: manual
